plugins:
  - serverless-offline

service: serverless-nuxt
provider:
  name: aws
  runtime: nodejs8.10
  region: ap-northeast-1

functions:
  entry:
#    handler: handler.render
#    handler: dist/server.render
    handler: server/dist/index.render
    events:
      - http:
          path: /
          method: get
          cors: true
      - http:
          path: '{proxy+}'
          method: get
          cors: true
