plugins:
  - serverless-offline

service: serverless-nuxt 
provider:
  name: aws
  runtime: nodejs6.10
  region: ap-northeast-1

functions:
  entry:
    handler: entry.handler
    events:
      - http:
          path: /
          method: get
